import 'package:food_bite/ui/bottom_sheets/notice/notice_sheet.dart';
import 'package:food_bite/ui/dialogs/info_alert/info_alert_dialog.dart';
import 'package:food_bite/ui/views/home/home_view.dart';
import 'package:food_bite/ui/views/startup/startup_view.dart';
import 'package:stacked/stacked_annotations.dart';
import 'package:stacked_services/stacked_services.dart';
import 'package:food_bite/ui/views/onboarding/onboarding_view.dart';
import 'package:food_bite/ui/views/login/login_view.dart';
import 'package:food_bite/ui/views/signup/signup_view.dart';
import 'package:food_bite/ui/views/add_address/add_address_view.dart';
import 'package:food_bite/ui/views/add_phone/add_phone_view.dart';
import 'package:food_bite/ui/views/verify_otp/verify_otp_view.dart';
import 'package:food_bite/ui/bottom_sheets/select_country_code/select_country_code_sheet.dart';
import 'package:food_bite/ui/views/add_email/add_email_view.dart';
import 'package:food_bite/ui/views/verify_email/verify_email_view.dart';
import 'package:food_bite/ui/views/reset_password/reset_password_view.dart';
import 'package:food_bite/ui/views/confirm/confirm_view.dart';
import 'package:food_bite/ui/views/navigation/navigation_view.dart';
import 'package:food_bite/services/app_states_service.dart';
import 'package:food_bite/services/local_storage_service.dart';
import 'package:food_bite/ui/views/menu/menu_view.dart';
import 'package:food_bite/ui/views/cart/cart_view.dart';
import 'package:food_bite/ui/views/orders/orders_view.dart';
import 'package:food_bite/ui/views/profile/profile_view.dart';
import 'package:food_bite/ui/views/track/track_view.dart';
import 'package:food_bite/ui/views/history/history_view.dart';
import 'package:food_bite/ui/views/item_details/item_details_view.dart';
import 'package:food_bite/ui/views/checkout/checkout_view.dart';
import 'package:food_bite/ui/views/add_payment/add_payment_view.dart';
import 'package:food_bite/ui/views/confirmation/confirmation_view.dart';
import 'package:food_bite/ui/views/order_details/order_details_view.dart';
import 'package:food_bite/ui/views/rate_driver/rate_driver_view.dart';
import 'package:food_bite/ui/views/rate_your_food/rate_your_food_view.dart';
import 'package:food_bite/services/file_picker_service.dart';
import 'package:food_bite/services/local_storage_service.dart';
import 'package:food_bite/ui/bottom_sheets/select_photo/select_photo_sheet.dart';
import 'package:food_bite/ui/views/confirm_feedback/confirm_feedback_view.dart';
import 'package:food_bite/ui/views/account_information/account_information_view.dart';
import 'package:food_bite/ui/views/change_password/change_password_view.dart';
import 'package:food_bite/ui/views/delivery_locations/delivery_locations_view.dart';
import 'package:food_bite/ui/views/payment_methods/payment_methods_view.dart';
import 'package:food_bite/ui/views/payment_cards/payment_cards_view.dart';
import 'package:food_bite/ui/views/add_card/add_card_view.dart';
import 'package:food_bite/services/api_service.dart';
import 'package:food_bite/services/auth_service.dart';
import 'package:food_bite/services/database_service.dart';

import '../core/config/config.dart';
import 'package:food_bite/services/database_service.dart';
import 'package:food_bite/ui/dialogs/alert/alert_dialog.dart';
import 'package:food_bite/ui/views/table_reservation/table_reservation_view.dart';
import 'package:food_bite/ui/bottom_sheets/rate_item/rate_item_sheet.dart';
import 'package:food_bite/ui/bottom_sheets/edit_address/edit_address_sheet.dart';
import 'package:food_bite/services/order_service.dart';
// @stacked-import

@StackedApp(
  routes: [
    MaterialRoute(page: HomeView),
    MaterialRoute(page: StartupView),
    MaterialRoute(page: OnboardingView),
    MaterialRoute(page: LoginView),
    MaterialRoute(page: SignupView),
    MaterialRoute(page: AddAddressView),
    MaterialRoute(page: AddPhoneView),
    MaterialRoute(page: VerifyOtpView),
    MaterialRoute(page: AddEmailView),
    MaterialRoute(page: VerifyEmailView),
    MaterialRoute(page: ResetPasswordView),
    MaterialRoute(page: ConfirmView),
    MaterialRoute(page: NavigationView),
    MaterialRoute(page: MenuView),
    MaterialRoute(page: CartView),
    MaterialRoute(page: OrdersView),
    MaterialRoute(page: ProfileView),
    MaterialRoute(page: TrackView),
    MaterialRoute(page: HistoryView),
    MaterialRoute(page: ItemDetailsView),
    MaterialRoute(page: CheckoutView),
    MaterialRoute(page: AddPaymentView),
    MaterialRoute(page: ConfirmationView),
    MaterialRoute(page: OrderDetailsView),
    MaterialRoute(page: RateDriverView),
    MaterialRoute(page: RateYourFoodView),
    MaterialRoute(page: ConfirmFeedbackView),
    MaterialRoute(page: AccountInformationView),
    MaterialRoute(page: ChangePasswordView),
    MaterialRoute(page: DeliveryLocationsView),
    MaterialRoute(page: PaymentMethodsView),
    MaterialRoute(page: PaymentCardsView),
    MaterialRoute(page: AddCardView),
    MaterialRoute(page: TableReservationView),
// @stacked-route
  ],
  dependencies: [
    LazySingleton(classType: BottomSheetService),
    LazySingleton(classType: DialogService),
    LazySingleton(classType: NavigationService),
    LazySingleton(classType: AppStatesService),
    LazySingleton(classType: LocalStorageService),
    LazySingleton(classType: FilePickerService),
    LazySingleton(classType: ApiService),
    LazySingleton(classType: AuthService),
    LazySingleton(classType: DatabaseService),
    LazySingleton(classType: Config),
    LazySingleton(classType: OrderService),
// @stacked-service
  ],
  bottomsheets: [
    StackedBottomsheet(classType: NoticeSheet),
    StackedBottomsheet(classType: SelectCountryCodeSheet),
    StackedBottomsheet(classType: SelectPhotoSheet),
    StackedBottomsheet(classType: RateItemSheet),
    StackedBottomsheet(classType: EditAddressSheet),
// @stacked-bottom-sheet
  ],
  dialogs: [
    StackedDialog(classType: InfoAlertDialog),
    StackedDialog(classType: AlertDialog),
// @stacked-dialog
  ],
)
class App {}
